### ISSUE TITLE
Swift version this was built with is outdated on newer version of xcode

### ISSUE THREAD

**Issue by milano23** [LinusU/flutter_web_auth#1]
I created a new flutter project.  I have added flutter_web_auth plugin to the yaml file and import in main.dart. Following the given example i added some parameters to use the plugin to authenticate and retrieve the response_type code.  I ran flutter run in the terminal and received the following output:

> Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

> Xcode's output:
> ↳
>     === BUILD TARGET flutter_web_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
>     The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

> Could not build the application for the simulator.
> Error launching application on iPhone X.

I opened xcode and tried to build in there to see if i could get more details from the error and received the following:

<img width="419" alt="Screenshot 2019-03-20 12 04 36" src="https://user-images.githubusercontent.com/4675905/54699990-79fdab80-4b08-11e9-9127-56dbbe81ec2b.png">

**Comment by LinusU** [comment]
Sorry for the delay in answering this, I've been out traveling and just got back.

I think it's because I'm not specifying Swift version in the Podspec. I'll add that and we can see if it fixes it 👌

**Comment by LinusU** [comment]
Should be fixed by https://github.com/LinusU/flutter_web_auth/commit/f2cf226abc1ee4b18283efa0068d278362092ae4, released as 0.1.1 🚢
