### ISSUE TITLE
How do I redirect to my mobile app?

### ISSUE THREAD

**Issue by andres-alba** [LinusU/flutter_web_auth#103]
can someone share implementation of this with flutter?  I see no examples of actual applications authenticating with this package.

**Comment by Konradrundfunk** [comment]
I am also stuck with a simular issue. I looked at the implementation and couldn't see any references to a redirect to the iOS app. I am considering on implementing a similar function by myself to get it to work.

**Comment by ThomasAunvik** [comment]
I use the combination with OpenIdConnect library to generate the authentication url and to do the code exchange, supporting PKCE at the same time too.

**Comment by mo-aro-etailer** [comment]
Your schema must be valid or else this wont work.

You can not use underscore or space

check https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore for valid schema

**Comment by mo-aro-etailer** [comment]
I had the same problem too and fixed it this way 

Your schema must be valid or else this wont work.

You can not use underscore or space

check https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore for valid schema

**Comment by oshju** [comment]
> I had the same problem too and fixed it this way
> 
> Your schema must be valid or else this wont work.
> 
> You can not use underscore or space
> 
> check https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore for valid schema

i have same issue ,can you share you code?

**Comment by LinusU** [comment]
Troubleshooting has now been merged into this repo 🎉 

Please take a look and see if it helps you, if not we can reopen

https://github.com/LinusU/flutter_web_auth#troubleshooting

**Comment by Konradrundfunk** [comment]
Thanks!
