### ISSUE TITLE
targetSdkVersion 31

### ISSUE THREAD

**Issue by leekim611** [LinusU/flutter_web_auth#104]
When performing certain tasks, this package was of great help.

But, it is not working when I run with the actual android device.

So, please update the code.

<manifest>
  <application>

    <activity android:name="com.linusu.flutter_web_auth.CallbackActivity"
      android:exported="true" >   // add this line
      <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="YOUR_CALLBACK_URL_SCHEME_HERE" />
      </intent-filter>
    </activity>

  </application>
</manifest>

**Comment by leekim611** [comment]
I checked that this code was applied!!

But, It has not yet been applied in pub.dev.

Thank you.

**Comment by LinusU** [comment]
> android:exported="true"

This has been added now, will cut a release shortly 👍
