### ISSUE TITLE
Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

### ISSUE THREAD

**Issue by arrmani88** [LinusU/flutter_web_auth#109]
First of all thanks for this package.
In the documentation that's provided in pub.dev it's mentioned that the following activity needs to be added to my AndroidManifest.xml:
```
    <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
      <intent-filter android:label="flutter_web_auth">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="YOUR_CALLBACK_URL_SCHEME_HERE" />
      </intent-filter>
    </activity>
```

This causes an error, because when you use `intent-filter` starting from android 12 (SDK 31), the attribute android:exported must be set explicitly to false or true.
So I think this needs to be added to the documentation:

```
       <activity
           android:name="com.linusu.flutter_web_auth.CallbackActivity"
           android:exported="true"> <!--THIS SHOULD BE ADDED-->
```

**Comment by Alex-Dobrynin** [comment]
What stops you to add this when you daclaring com.linusu.flutter_web_auth.CallbackActivity ?

**Comment by pchasco** [comment]
> android:exported="true"

I believe he is saying that the documentation needs to be updated. He is not saying he cannot add it.

**Comment by LinusU** [comment]
Documentation is updated! 🎉
