### ISSUE TITLE
YOUR_CALLBACK_URL_SCHEME_HERE ? What is this, it's not explained!

### ISSUE THREAD

**Issue by emailsubjekt** [LinusU/flutter_web_auth#12]
I see in the official example we have to define this. What is it and is there an example?

**Comment by lucavinci** [comment]
In your oauth2 workflow, at the end (successful or unsuccessful auth) the user is redirected to an url like emailapp://oauth-callback#loginsuccess

in that case the scheme would be emailapp

**Comment by LinusU** [comment]
Yeah, you can set it to whatever you want, as long as you get your oauth2 page to redirect to it

**Comment by LinusU** [comment]
I'd be happy to accept a pull request that clarifies the documentation around it. But as it is right now the documentation assumes that you already know the technicalities of OAuth2 if you want to implement that, since this library isn't specifically tied to OAuth2 🤔
