### ISSUE TITLE
Callback URL Scheme doesn't work after user refreshes page on website.

### ISSUE THREAD

**Issue by niteshsh4rma** [LinusU/flutter_web_auth#124]
I've working on a oauth website, sometimes redirect fails due to API, but when I refresh it redirects to the current callbackScheme in the android/ios, but `flutter_web_auth` doesn't work as expected and shows invalid URL screen.

**Comment by mo-aro-etailer** [comment]
I had the same problem too and fixed it this way

Your schema must be valid or else this wont work.

You can not use underscore or space

check https://stackoverflow.com/questions/9142309/may-url-scheme-contain-an-underscore for valid schema
