### ISSUE TITLE
How open ASWebAuthenticationSession  full screen

### ISSUE THREAD

**Issue by postflow** [LinusU/flutter_web_auth#125]
Hi! Thanks for plugin! One small question:
How open ASWebAuthenticationSession  full screen on IOS 11 and above ?

**Comment by LinusU** [comment]
Hello,

Unfortunately I cannot find anything in the documentation around `ASWebAuthenticationSession` suggesting this would be possible. If you can show some native code that can do this, I would be happy to implement it.

But until then I'll close this since it isn't actionable for me...
