### ISSUE TITLE
Official example differs from advice on library page 

### ISSUE THREAD

**Issue by emailsubjekt** [LinusU/flutter_web_auth#13]
Official code example is different than the example on the library page. Also the example on the library page google auth example code is just a bunch of methods, where are they to be called, in what order?!? Where is the complete Oatuth Google signin web example that can be tried out? I've tried the github example, it has HTML in it I guess for building the auth page, however, it doesn't work. I made a new fresh project and copied it into there however I keep getting web errors like this 

IN RUN 
This application is not configured to build on the web.
To add web support to a project, run `flutter create .`.

THEN IN TERMINAL 
Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\FlutterDell\Test126-FlutterFirebaseFire\flutter_web_auth-master>flutter create .
"flutter_web_auth-master" is not a valid Dart package name.

From the [Pubspec format description](https://www.dartlang.org/tools/pub/pubspec.html):

**DO** use `lowercase_with_underscores` for package names.

Package names should be all lowercase, with underscores to separate words,
`just_like_this`.  Use only basic Latin letters and Arabic digits: [a-z0-9_].
Also, make sure the name is a valid Dart identifier -- that it doesn't start
with digits and isn't a reserved word.

-----------
I mean seriously, why should this be so hard? It should be a simple list of method when called they just work, not a ton of code, you gotta change this and this and this and this and find how this works, I mean what the hell guys. Even the official google signin web example doesn't work. Does anyone even have an example that works and doesn't require 2 dozen variables from all over the place written in a certain manner from the definite undefined place.

**Comment by LinusU** [comment]
> Where is the complete Oatuth Google signin web example that can be tried out?

There isn't one. It would be great if you could create one and publish on GitHub. I'd be happy to link to it! 🙌 

I'm having a hard time finding anything actionable for me in this issue, so I will close it for now.

If you would like to create the example in a GitHub repo but get stuck, please link me to it and tell me on what you got stuck on here and I'd be happy to help you forward!
