### ISSUE TITLE
 FlutterWebAuth.authenticate never returns

### ISSUE THREAD

**Issue by eternalparquet** [LinusU/flutter_web_auth#130]
For Flutter Web the  FlutterWebAuth.authenticate method never returns, the url generated is not returned.
The callbackUrlScheme has an /auth.html page.
I am using it for ebay oauth.
Why it doesn't returns?

**Comment by linkkader** [comment]
@eternalparquet have you find solution ? i have same problem

**Comment by harrowmykel** [comment]
Please read the trouble shooting section at the bottom of the readme.md in

https://github.com/harrowmykel/flutter_web_auth#troubleshooting

**Comment by LinusU** [comment]
Troubleshooting has now been merged into this repo 🎉 

Please take a look and see if it helps you, if not we can reopen

https://github.com/LinusU/flutter_web_auth#troubleshooting
