### ISSUE TITLE
Authenticaion seen as canceled when using the normal flow - Android

### ISSUE THREAD

**Issue by ElDuderini** [LinusU/flutter_web_auth#134]
When the call back for authentication happens on android, the plugin sees it as the user canceling the login. Here is how I implement it:
![Screenshot 2022-08-04 at 16 40 45](https://user-images.githubusercontent.com/44909968/182875402-21faac21-d7ce-4915-8580-2548ca1b6020.png)
![Screenshot 2022-08-04 at 16 41 56](https://user-images.githubusercontent.com/44909968/182875657-3842f7c8-bca0-48a2-acc9-5fa852aa70b9.png)
Here is the error:
![Screenshot 2022-08-04 at 16 42 49](https://user-images.githubusercontent.com/44909968/182875847-9f360f60-f06e-4355-9957-3e1f0b55489c.png)
I also tried setting the launch mode of the android app to a single instance since I thought that would fix the issue of the callback data not being retrieved properly, but it didn't work. iOS works as intended.

**Comment by paul-charlton** [comment]
@ElDuderini did you get anywhere with this issue?  Running into the same problem.

**Comment by LinusU** [comment]
> Basically, I set up the android manifest incorrectly, I needed to set up a separate activity solely for the behavior of the plugin. When this was implemented, this issue no longer showed up where the data was successfully being transferred back into the application.

We have added a troubleshooting section to the readme that hopefully should make this clearer!

https://github.com/LinusU/flutter_web_auth#troubleshooting 🎉 

Let me know if you still need more help
