### ISSUE TITLE
Example with localhost

### ISSUE THREAD

**Issue by mikeybellissimo** [LinusU/flutter_web_auth#140]
Hi,
Really nice work on the package! I am currently navigating to my custom solution on a different server but since I am on localhost it seems that there's no easy way to have the callback scheme work. Do you mind providing an example of how it should work when you're on localhost? 

For example, what would a good callback scheme be and what specific address, using this callback scheme, would my custom solution redirect to? 
Thanks!
Michael

**Comment by LinusU** [comment]
Hello,

You can just make up a callback scheme, e.g. `mikeybellissimoscoolapp`. Then you redirect the user to `mikeybellissimoscoolapp://`.

See the new troubleshooting chapter for more info: https://github.com/LinusU/flutter_web_auth#troubleshooting-oauth-redirects

Happy hacking!
