### ISSUE TITLE
0.5.0 introduces breaking change for web auth

### ISSUE THREAD

**Issue by parkerleblanc01** [LinusU/flutter_web_auth#146]
**Temporary solution: Rollback to 0.4.0**

0.5.0 required auth.html route no longer works as it used to for flutter web. An invalid callback schema error is thrown when passing in a url as a callback such as http://localhost:3000/auth.html

On 0.4.0 (which still seems to work on flutter 3), I was doing the following logic to account for the web url. I'm unsure how to pass my url with the new implementation.
```dart
final currentUri = Uri.base;
final webRedirect = Uri(
  host: currentUri.host,
  scheme: currentUri.scheme,
  port: currentUri.port,
  path: '/auth.html',
);

final redirectUri = kIsWeb ? webRedirect.toString() : "$_REDIRECT_SCHEME://oauth/callback";

final url = Uri.https(_CWA_BASE_URL, '/oauth/authorize', {
  'response_type': 'code',
  'client_id': _CLIENT_ID,
  'redirect_uri': redirectUri,
  'scope': 'openid',
});

// Get auth code
final callbackUrl = await FlutterWebAuth.authenticate(
    url: url.toString(),
    callbackUrlScheme: kIsWeb ? webRedirect.toString() : _REDIRECT_SCHEME,
);
```

**Comment by LinusU** [comment]
`callbackUrlScheme` should be just the url scheme, not an entire url. On the web platform the value of `callbackUrlScheme` is ignored.

I think that the following change should fix your problem:

```diff
 // Get auth code
 final callbackUrl = await FlutterWebAuth.authenticate(
     url: url.toString(),
-    callbackUrlScheme: kIsWeb ? webRedirect.toString() : _REDIRECT_SCHEME,
+    callbackUrlScheme: _REDIRECT_SCHEME,
 );
```

**Comment by parkerleblanc01** [comment]
Just tried this @LinusU, works as expected. Thank you for your help!
