### ISSUE TITLE
fatal error: module 'flutter_web_auth' not found

### ISSUE THREAD

**Issue by JoellyR** [LinusU/flutter_web_auth#18]
When running the project on a simulator everything seems to work fine. Once i tried to deploy to an actual device I get the following error:  

iOS Version - 13.0

Xcode Version - 11.3.1 

Flutter Version - 1.12.13+hotfix.8

Building AOT snapshot in release mode (ios-release)...          
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             30.5s
    Built to build/aot/.
    warning: parsing line table prologue at offset 0x6f697463 found unsupported
    version 0x00
    warning: line table parameters mismatch. Cannot emit.
    note: while processing
    /Users/<Username>/Documents/flutter_test_app/build/aot/armv7/snapsho
    t_assembly.o
    Project /Users/<Username>/Documents/flutter_test_app built and
    packaged successfully.
    /Users/<Username>/Documents/flutter_test_app/ios/Runner/GeneratedPlu
    ginRegistrant.m:10:9: fatal error: module 'flutter_web_auth' not found
    @import flutter_web_auth;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    /Users/<Username>/Documents/flutter_test_app/ios/Runner/GeneratedPlu
    ginRegistrant.m:10:9: fatal error: module 'flutter_web_auth' not found
    @import flutter_web_auth;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error running application on iPhone.

**Comment by ryan-sf** [comment]
I can verify that I am seeing the same error. https://github.com/flutter/flutter/issues/53573#issuecomment-608624839

**Comment by bionara** [comment]
Same here - any known fix?

**Comment by bionara** [comment]
> When running the project on a simulator everything seems to work fine. Once i tried to deploy to an actual device I get the following error:
> 
> iOS Version - 13.0
> 
> Xcode Version - 11.3.1
> 
> Flutter Version - 1.12.13+hotfix.8
> 
> Building AOT snapshot in release mode (ios-release)...
> Building App.framework for arm64...
> 
> ```
> Building App.framework for armv7...
> Building AOT snapshot in release mode (ios-release)...             30.5s
> Built to build/aot/.
> warning: parsing line table prologue at offset 0x6f697463 found unsupported
> version 0x00
> warning: line table parameters mismatch. Cannot emit.
> note: while processing
> /Users/<Username>/Documents/flutter_test_app/build/aot/armv7/snapsho
> t_assembly.o
> Project /Users/<Username>/Documents/flutter_test_app built and
> packaged successfully.
> /Users/<Username>/Documents/flutter_test_app/ios/Runner/GeneratedPlu
> ginRegistrant.m:10:9: fatal error: module 'flutter_web_auth' not found
> @import flutter_web_auth;
>  ~~~~~~~^~~~~~~~~~~~~~~~
> 1 error generated.
> /Users/<Username>/Documents/flutter_test_app/ios/Runner/GeneratedPlu
> ginRegistrant.m:10:9: fatal error: module 'flutter_web_auth' not found
> @import flutter_web_auth;
>  ~~~~~~~^~~~~~~~~~~~~~~~
> 1 error generated.
> note: Using new build system
> note: Planning build
> note: Constructing build description
> ```
> 
> Could not build the precompiled application for the device.
> 
> Error running application on iPhone.

any fix for this?

**Comment by Niggelgame** [comment]
I think it is because currently the Plugin does only support arm64. Try checking „only build for current device“ in Xcode in the build settings. I created a PR #29 , with which you could still build it, but it isn‘t supported currently.

**Comment by LinusU** [comment]
I believe that this is fixed in the latest version, happy to reopen if it isn't

**Comment by Ulukbek-01** [comment]
any fixes?
