### ISSUE TITLE
CallbackActivity not invoke

### ISSUE THREAD

**Issue by Gperez88** [LinusU/flutter_web_auth#21]
i have configured  activity callback on my manifest but it's not called

`    
        <activity android:name="com.linusu.flutter_web_auth.CallbackActivity">
            <intent-filter android:label="flutter_web_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" />
            </intent-filter>
        </activity>`

**Comment by Michael24884** [comment]
I’m also having this problem

**Comment by fringefilmsoz** [comment]
I'm also having this problem. All callbacks return in browser as 'This site cannot be reached."

![image](https://user-images.githubusercontent.com/10631413/83881883-a7259080-a784-11ea-9f4f-c3132db3f398.png)

**Comment by RaulMarquezInclan** [comment]
The android scheme must have the format:
domain.company.some_name
and must match the redirect uri configured in the auth server

**Comment by danielmintz** [comment]
> The android scheme must have the format:
> domain.company.some_name
> and must match the redirect uri configured in the auth server

I have the same problem but don't really understand the answer. sorry.  Could you maybe break it down with an example? Also, where do you configure the auth server? thanks

**Comment by LinusU** [comment]
Please read our new troubleshooting guide:
https://github.com/LinusU/flutter_web_auth#troubleshooting

In the screenshot above it looks like a final `://` is missing when redirecting.
