### ISSUE TITLE
Logoff

### ISSUE THREAD

**Issue by intellitour** [LinusU/flutter_web_auth#24]
I can't logoff after I login. The device's browser stores auth data and I cannot purge it. 

**How to reproduce:**

1. Log in
2. Do something in your app
3. Logoff in your app by any means
4. Attempt to log in with another user

**Comment by LinusU** [comment]
Unfortunately there is nothing that we can do from the app side here, you need to work with your OAuth provider to see how this should be handled. Maybe there is a query parameter that you can append to force a profile selection or similar?

**Comment by LinusU** [comment]
Closing this for now, but if there is anything we can do from this module I'll be happy to re-open!
