### ISSUE TITLE
redirectURL cannot working

### ISSUE THREAD

**Issue by phantrungphat** [LinusU/flutter_web_auth#30]
Hello, i'm writting a Spotify Oauth2. i'm facing this issue when i authenticate and redirect to my app.
![image](https://user-images.githubusercontent.com/46749741/80555877-d3b6f180-89fb-11ea-8a9f-04fc9f76e3f1.png)
My callbackUrlScheme: 
![image](https://user-images.githubusercontent.com/46749741/80555958-27293f80-89fc-11ea-9b6d-6b5260d165f9.png)
url: 
![image](https://user-images.githubusercontent.com/46749741/80555978-3a3c0f80-89fc-11ea-95c6-47e8bf7a5f94.png)
And the FlutterWebAuth.authenticate:
![image](https://user-images.githubusercontent.com/46749741/80556012-5a6bce80-89fc-11ea-99b3-fd1914792173.png)
I config in my AndroidManifest.xml:
![image](https://user-images.githubusercontent.com/46749741/80556072-8edf8a80-89fc-11ea-8f12-97d117256656.png)

**Comment by inhumantsar** [comment]
![image](https://user-images.githubusercontent.com/494253/81340816-1b7dee80-9076-11ea-8203-e5fc93d95787.png)

i'm having trouble with this as well, but i think i think this might be a problem. shouldn't the callbackUrlScheme just be `spotify-app-album`?

**Comment by sallaben** [comment]
> ![image](https://user-images.githubusercontent.com/494253/81340816-1b7dee80-9076-11ea-8203-e5fc93d95787.png)

Yes you are correct it just wants `spotify-app-album` in this case @phantrungphat
