### ISSUE TITLE
The the auth provider has somekind of 2fa then this plugin fails

### ISSUE THREAD

**Issue by prasadsunny1** [LinusU/flutter_web_auth#32]
Reason: As soon as user puts the custom tabs activity to the background to go and collect 2FA code, The custom tab is killed because of NoHistory flag.

I have removed this flag and it works fine. 
If this solution looks ok then ask me to send a PR.

**Comment by LinusU** [comment]
Sure, PR welcome 👍

**Comment by prasadsunny1** [comment]
Does this PR look good.

**Comment by LinusU** [comment]
Fixed by #33
