### ISSUE TITLE
Callback Scheme Not Captured

### ISSUE THREAD

**Issue by inhumantsar** [LinusU/flutter_web_auth#34]
AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.tacotrucks">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="tacotrucks"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            ...
        </activity>
        <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
            <intent-filter android:label="flutter_web_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="tacotrucks" android:host="moo" />
            </intent-filter>
        </activity>
        ...
    </application>
</manifest>
```

Authenticate call:
```
    final redirectUri =
        Uri(scheme: 'tacotrucks', host: 'moo', path: 'oauth2redirect');
    ...
    final result = await FlutterWebAuth.authenticate(
        url: authUrl.toString(), callbackUrlScheme: 'tacotrucks');
```

I'm able to auth against the provider but when it sends me to my redirectUrl (`tacotrucks://moo/oauth2redirect?state=tacotrucks&code=....`), I get `ERR_UNKNOWN_URL_SCHEME`.

Am I missing something?

edit for more details: This is a brand new Flutter project and this oauth flow is the only thing in it at the moment. I'm attempting to auth against Reddit. The webview opens correctly and I'm able to login to Reddit and the code it provides in the redirect URL params is valid, but attempts to redirect the webview to this custom scheme end with that error. The test device is a physical Pixel XL running the latest public release of stock Android 10 and the default browser is Chrome.

**Comment by inhumantsar** [comment]
took another crack at this. realised i might have misunderstood the activity section. removed the new activity and move the intent filter into my main application activity. 

i'm able to trigger the intent manually with `adb shell am start -W -a android.intent.action.VIEW -d "tacotrucks://moo/oauth2request"` but not via this package

**Comment by inhumantsar** [comment]
tried a few more things but haven't been able to get it going. pushed the stripped down project up to https://github.com/inhumantsar/tacotrucks

**Comment by hynra** [comment]
Same problem here.

**Comment by inhumantsar** [comment]
came back to this over the weekend and found my problem.

my test device has a reddit client on it and it was capturing the authorisation webview. so the authorisation page would come up, i could auth the app, the redirect would fire but fail with "scheme not found" because the reddit client isn't configured to handle that scheme.

i can use an emulator or go into the other app's `App Info` pane, then `Open by default`, and change `Open supported links` to `Ask every time` to fix this issue.
