### ISSUE TITLE
doesn,t work after update to version 

### ISSUE THREAD

**Issue by AlvaroMenezes** [LinusU/flutter_web_auth#35]
I solve it open my project in xCode and run build to find possible error, so when find error line xcode  suggest add automatically  **if #available** before a version validation and it works. Sorry I close xcode after works and I dont know where the error, but on Android Studio still have the log. I hope it help.

/Users/robertorosa/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.3/ios/Classes/SwiftFlutterWebAuthPlugin.swift:29:33: error: 'SFAuthenticationError' is only available in iOS 11.0 or newer
                            if case SFAuthenticationError.canceledLogin = err {
                                    ^
    /Users/robertorosa/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.3/ios/Classes/SwiftFlutterWebAuthPlugin.swift:29:33: note: add 'if #available' version check
                            if case SFAuthenticationError.canceledLogin = err {
                                    ^
    /Users/robertorosa/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.3/ios/Classes/SwiftFlutterWebAuthPlugin.swift:13:17: note: add @available attribute to enclosing instance method
        public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
                    ^
    /Users/robertorosa/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.3/ios/Classes/SwiftFlutterWebAuthPlugin.swift:6:14: note: add @available attribute to enclosing class
    public class SwiftFlutterWebAuthPlugin: NSObject, FlutterPlugin {
                 ^
    /Users/robertorosa/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.3/ios/Classes/SwiftFlutterWebAuthPlugin.swift:18:17: warning: variable 'sessionToKeepAlive' was written to, but never read
                var sessionToKeepAlive: Any? = nil // if we do not keep the session alive, it will get closed immediately while showing the dialog

**Comment by LinusU** [comment]
Sorry abut this, and thanks for the bug report.

Could you try applying the patch in #36 locally and see if it solves it for you? Thanks!

**Comment by LinusU** [comment]
Fixed in [🚢 0.2.4 / 2020-05-12](https://github.com/LinusU/flutter_web_auth/releases/tag/0.2.4)
