### ISSUE TITLE
Chrome Tabs still visible on app close

### ISSUE THREAD

**Issue by Faiyyaz** [LinusU/flutter_web_auth#37]
Hi,

Thanks for such a great library

I still see the chrome tab on android after closing the app after doing login using the libary.

**Comment by Faiyyaz** [comment]
Maybe you can refer this link and try

https://gist.github.com/im182cm/2c7723d42b2d7091af6c493b97b732b7

**Comment by DanielEberl** [comment]
#33 This Change introduced this behaviour

**Comment by flutcon** [comment]
I see this as well - locally reverting #33 works for me. I think we need to find a solution to resolve both issues.

**Comment by okrad** [comment]
Some of the users of my library, which relies on flutter_web_auth, reported a similar issue (teranetsrl/oauth2_client#26). 

@LinusU, are you considering merging the pull request made by @ThexXTURBOXx or are there any non obvious side effects?

Thank you for your work!

**Comment by ThexXTURBOXx** [comment]
@okrad I don't know, if the developer is still actively developing this project. For the time being, you can just use my patch using a override, like this:
```
dependency_overrides:
  flutter_web_auth:
    git: 'https://github.com/ThexXTURBOXx/flutter_web_auth.git'
```

**Comment by Guillaume-Vacelet** [comment]
@ThexXTURBOXx 
I don't know if i'm missing a step, but your patch doesn't work for me. 
When `FlutterWebAuth.authenticate(url: url, callbackUrlScheme: callbackUrlScheme, saveHistory: false);` ends successfully, the browser tab used to authenticate is still alive.
So i can't log the user out, because every time i make a new call of `FlutterWebAuth.authenticate()`, it logs in automatically with the old tab.

I followed your instructions and edited `pubspec.yaml`, added `saveHistory: false`, deleted the folders you describe and `pub get`. Here is my `flutter doctor -v`, in hope someone can help me :

```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.2 at /home/vguillaume/snap/flutter/common/flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/vguillaume/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/local/lib/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/local/lib/android-studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM G935F (mobile) • ad0b160398f242dc2c • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by Guillaume-Vacelet** [comment]
The only solution i found is to manually close the custom chrome tab handling the oauth2.
As long as it is alive, it is auto-logging me in my app without letting me enter new credentials.

**Comment by SogoGolf** [comment]
ok thanks. i get the feeling this lib isn't being maintained, plus it doesn't appear to work well at all on Android

**Comment by ThexXTURBOXx** [comment]
My solution works for this issue at least. Overall, the library works pretty well on Android, except for this issue here.
And yes, the lib doesn't seem to be maintained right now. Maybe someone will pick up the torch at some point in the future, though.

**Comment by SogoGolf** [comment]
thanks @ThexXTURBOXx yes I saw your fork and made use of it is great thanks.

one thing that has me stumped on Android with this lib is that if (local) storage is enabled to keep the token - and then you delete that token from local storage - this lib keeps authenticating with that same token...! have you seen this before ?

**Comment by LinusU** [comment]
There is now a flag `preferEphemeral` which you can pass as `true` in order to put the `NoHistory` flag back.

Please let me know if there is anything else that needs to be done here ☺️
