### ISSUE TITLE
Option to send headers to the "web view"

### ISSUE THREAD

**Issue by akvus** [LinusU/flutter_web_auth#4]
Would it be possible to add an option in the library to add headers to the request?

For example on Android:

`    intent.intent.putExtra(Browser.EXTRA_HEADERS, Bundle().apply {
        putString(headerName, headerValue)
      })
`

**Comment by akvus** [comment]
I have a custom auth service which requires me to send some information to it either as a header or as a cookie.

**Comment by LinusU** [comment]
Are you only interested in Android? or do you have an idea on how to make it work on iOS?

**Comment by akvus** [comment]
I don't have much iOS experience and I had no time to look into the iOS version, but I will need that in future.

**Comment by LinusU** [comment]
As far as I can tell, iOS doesn't offer the option to send in extra headers, so you'll have to work around this in another way...

**Comment by akvus** [comment]
Indeed, the headers cannot be included on iOS as it is with Custom Chrome Tabs. The alternative would be a webview.
