### ISSUE TITLE
Logging out

### ISSUE THREAD

**Issue by RaulMarquezInclan** [LinusU/flutter_web_auth#40]
I have been trying to logout of the session using the logout endpoint.

I suppose when dealing with these flows they're all standardized no matter who the auth server provider is right?

What's the correct way to logout?

With the auth server I'm using, Okta, it says the following:

```
Note: When making requests to the /logout endpoint, the browser (user agent) should be redirected to the endpoint. You can't use AJAX with this endpoint.
```
I can construct the logout url just fine, but it just sends me to a 400 erro okta page.

This is the documentation:
https://developer.okta.com/docs/reference/api/oidc/#logout

Any ideas?

Thanks.

**Comment by mvolpato** [comment]
Sometimes the logout URL is different from what you expect:

```dart
  static String _baseUri = 'https://your-auth-provider.com';
  // This specific provider appends an additional path to the basicURI, for logout only. ¯\_(ツ)_/¯
  static String _additionalPathLogout = '/oauth2/v1';
  static String _callbackUriScheme = 'your.callback.uri.scheme';
  static String _logoutRedirectUri = '$_callbackUriScheme:/logout';
```

then

```dart
String token = 'your-token';
String url = '$_baseUri$_additionalPathLogout/logout?id_token_hint=$token&post_logout_redirect_uri=$_logoutRedirectUri';
```

finally

```dart
await FlutterWebAuth.authenticate(url: url, callbackUrlScheme: _callbackUriScheme);
```

**Comment by adambolcsfoldi** [comment]
Calling `authenticate` to log out on iOS, since the method uses `ASWebAuthenticationSession`, presents this system dialog that asks the user if they want to sign, which is confusing.

![IMG_6851](https://user-images.githubusercontent.com/8832515/91994192-9d390c80-ed36-11ea-9ab8-baca26866119.PNG)

Or am I missing something/doing something wrong?

**Comment by mvolpato** [comment]
That is true.

I do not know about `ASWebAuthenticationSession`, with Okta this flow is needed, otherwise on the next login, the webpage will show only a textfield for the password, and no text field for the email address.

Maybe `ASWebAuthenticationSession` does not do that, and you can just revoke the token(s) and send the user to the login screen.

**Comment by adambolcsfoldi** [comment]
According to my [research](https://stackoverflow.com/a/61438262), if you just clear the token, the session would still remember the user for the next log-in. 

Best I found so far was to use the flag [`prefersEphemeralWebBrowserSession`] (https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc) (iOS >= 13). 
When set to `true` it foregoes the alert dialog above, but also the browser doesn't have your logged-in state from e.g. Facebook. 
Setting it to `false` when logging in, and `true` when logging out produces the desired behaviour: App Store-review compliant alert when logging in, but not when logging out.

**Comment by mvolpato** [comment]
Just to be clear (because you mention "clearing" tokens), I meant "revoke" tokens.

For instance, for Okta, you can have a look at [this page](https://developer.okta.com/docs/guides/sign-users-out/ios/sign-out-of-your-app/) for the difference.

**Comment by adambolcsfoldi** [comment]
Good point. We're using AWS Cognito, which seemingly does not have a way to revoke tokens.

We call their [logout endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html) which [does not invalidate any tokens](https://github.com/aws-amplify/amplify-js/issues/3435), but only clears the state of their UI. This needs to happen in the same `ASWebAuthenticationSession` as the log-in occurred in.

**Comment by LinusU** [comment]
I don't think that there is a solution available here provided what the platforms give us. I'd be very happy to reopen this if someone can find a solution that is possible using iOS/Android native APIs! 🚀
