### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by Fasuh** [LinusU/flutter_web_auth#43]
Hello,
i am getting crash while using the package, the console returns
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/Fasuh/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.4/ios/Classes/SwiftFlutterWebAuthPlugin.swift, line 15
2020-08-03 16:34:54.606148+0200 Runner[49403:1186691] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/Fasuh/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_auth-0.2.4/ios/Classes/SwiftFlutterWebAuthPlugin.swift, line 15
```

the code works on android without any problems, i am using it to connect with spotify:
```
FlutterWebAuth.authenticate(
      url:
      "https://accounts.spotify.com/authorize?client_id=$_clientId&redirect_uri=$_redirectUri&scope=$_scope&response_type=code",
      callbackUrlScheme: "yourname",
    );
```

@edit
i have fixed the issue, there is a problem while decoding the url for the app if one of the values contains a space, while android seems to ignore that, the ios threw out an error, i had to change
`  static const _scope = 'user-top-read user-library-read';`
to
`  static const _scope = 'user-top-read+user-library-read';`

**Comment by Sangwan5688** [comment]
@Fasuh what you used as redirect URI in Spotify URL. I am trying to make it work but couldn't get the authentication token.
