### ISSUE TITLE
'flutter_web_auth/flutter_web_auth-Swift.h' file not found

### ISSUE THREAD

**Issue by synt8x** [LinusU/flutter_web_auth#44]
I get this error when building the project and inspected the plugin and can't find the file.

**Comment by sushant-varanasi** [comment]
[https://stackoverflow.com/questions/32098696/import-swift-class-in-objective-c-mymodule-swift-h-file-not-found](https://stackoverflow.com/questions/32098696/import-swift-class-in-objective-c-mymodule-swift-h-file-not-found)
check out this link, it might be helpful.
