### ISSUE TITLE
Getting Platform Exception on Android

### ISSUE THREAD

**Issue by ewm003** [LinusU/flutter_web_auth#45]
Hoping to get some help. This is my first time using OAUTH2. I am currently just using a test app for my education to test the flow before I integrate it into my production app. I am authenticating with [Teamsnap API](https://developer.teamsnap.com/documentation/apiv3/authorization/), using the token flow. It is working great on iOS but on Android I have been running into issues. I think I got the call back issue fixed but now it looks like it authenticates but I get a null result from the authentication. Looks like the platform exception may be causing the issue.
<img width="610" alt="Screen Shot 2020-08-18 at 7 32 45 PM" src="https://user-images.githubusercontent.com/40442018/90582256-8321fa80-e18a-11ea-9e65-e1e761ed5caf.png">
I am not canceling the login, just putting in my information and then clicking login, then it goes back  to my app and I get the error above. 

Here is what my code looks like, 
<img width="794" alt="Screen Shot 2020-08-18 at 7 40 47 PM" src="https://user-images.githubusercontent.com/40442018/90582389-cf6d3a80-e18a-11ea-8263-b6e5d9de01d2.png">

And my android manifest in case you need it. 
<img width="685" alt="Screen Shot 2020-08-18 at 7 44 54 PM" src="https://user-images.githubusercontent.com/40442018/90582587-4f93a000-e18b-11ea-805a-3424bfeb001d.png">

Thanks in advance for your help!

**Comment by albertputrapurnama** [comment]
I'm experiencing the same issue!

**Comment by putrikarunia** [comment]
Getting the same issue with android. Any help would be much appreciated 🙏

**Comment by albertputrapurnama** [comment]
Hey I found the issue, it's because the `callbackUrlScheme` provided in the authenticate function is incorrect. 

@ewm003 try replacing your `callbackUrlScheme` from `hcassistant://ejappdev.com` to `hcassistant` and the redirect should be caught by the FlutterWebAuth properly.

**Comment by ewm003** [comment]
Thanks for looking at this!! I will give that a go and let you know how it turns out.

**Comment by ewm003** [comment]
That worked, it now gets the token from the server!! Thanks guys, it's amazing what another set of eyes will do, I had been staring at that code for a long time and hadn't even thought that would be the problem since it was working on the iOS version.
