### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by eldadfux** [LinusU/flutter_web_auth#49]
Hey @LinusU, it would be great if you could add hacktoberfest labels to some of the open issues on this repo. At appwrite/appwrite we usually get lots of support from the community during this month and we might be able to use that to push the project forward.

**Comment by LinusU** [comment]
Sorry for never commenting on this! I did go thru and added the "help wanted" label to a number of issues, and also added the "hacktoberfest" tag to the repository, but I must have forgotten to actually leave a comment 🙈
