### ISSUE TITLE
After successful authentication redirection from web page to application is not happening.

### ISSUE THREAD

**Issue by Mallikarjun7657** [LinusU/flutter_web_auth#51]
Am able to navigate to fitbit authentication page with flutter_web_auth plugin. But, after authentication it is not navigating back to my application.

**Below is my code: on pressing button am invoking the below method from flutter but it is not navigating back to the same page after successful authentication**
`  void authenticate() async {
    // Present the dialog to the user
    print('Before Authentication');
    final result = await FlutterWebAuth.authenticate(
      url: "https://www.fitbit.com/oauth2/authorize?response_type=token&client_id=22BZMN&expires_in=2592000&scope=activity%20nutrition%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight&redirect_uri=https://tekfriday.com", //TODO: add &prompt=login to shwo login screen every time.
      callbackUrlScheme: "tekfriday",
    );

// Extract token from resulting url
    final token = Uri.parse(result).queryParameters['token'];
    print('token');
    print(token);
  }`

**Here is my AndroidMainifest file**

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tekfriday.wear_poc">
    
    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Fitness"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity android:name="com.tekfriday.wear_poc.CallbackActivity" >
            <intent-filter android:label="flutter_web_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https://tekfriday.com" />
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`
Please let me know if there is any bug in my code.
Thank you.

**Comment by ThexXTURBOXx** [comment]
For some reason you are adding a wrong callback activity.
Change the package name of the callback activity to ``com.linusu.flutter_web_auth.CallbackActivity`` in your AndroidManifest.xml
