### ISSUE TITLE
How to suppress "This app and website..." popup ?

### ISSUE THREAD

**Issue by SogoGolf** [LinusU/flutter_web_auth#53]
thanks for the great component. on iOS 13+ we are seeing this popup every single time the app starts, even when there is still a valid session/token, which is annoying for users. it's an iOS driven alert, but is there a way to get rid of it ? 

some research seemed to indicate that adding a property on ```session``` might work -
```session.prefersEphemeralWebBrowserSession = true```

or is there another way to achieve this ?

![image](https://user-images.githubusercontent.com/19580787/98876228-ed201680-24d1-11eb-99e5-0392da7a26f8.png)

**Comment by SogoGolf** [comment]
yep that did the trick ```session.prefersEphemeralWebBrowserSession = true```

**Comment by rajd90** [comment]
i'm having the same issue...where do set `session.prefersEphemeralWebBrowserSession = true`?
or, is this coming as a fix in the next release?

**Comment by invaderb** [comment]
@rajd90 There looks to be a PR to add Epherial browsin, but if you want to test the change suggested above
https://github.com/LinusU/flutter_web_auth/pull/64

On line 52 of /ios/.symlinks/plugins/flutter_web_auth/ios/Classes/SwiftFlutterWebAuthPlugin.swift
you can add the flags to enable it.

**Comment by LinusU** [comment]
#64 added a `preferEphemeral` which you can pass as `true`, it will be released with #85
