### ISSUE TITLE
Redirection to activity after successful login doesn't work.

### ISSUE THREAD

**Issue by JAOOOOO** [LinusU/flutter_web_auth#56]
Everything works seamlessly until the point of popping up the webview and getting back to the app itself.

My implementation is: 
`final result = await FlutterWebAuth.authenticate(
              url: state.url, callbackUrlScheme: 'httpbin');`

and my manifest is 
`        <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
            <intent-filter android:label="flutter_web_auth">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https://httpbin.org" />
            </intent-filter>
        </activity>
`

**Comment by ahmetbugraozcan** [comment]
i have same issue. Did you find a solution?

**Comment by LinusU** [comment]
Can you try the example and see if that works for you:

https://github.com/LinusU/flutter_web_auth/tree/master/example

**Comment by ahmetbugraozcan** [comment]
> Can you try the example and see if that works for you:
> 
> https://github.com/LinusU/flutter_web_auth/tree/master/example

It works for me. I've been working for this for days. Thank you very much.
