### ISSUE TITLE
Class referenced in the manifest, com.linusu.flutter_web_auth.CallbackActivity, was not found in the project or the libraries

### ISSUE THREAD

**Issue by karezza** [LinusU/flutter_web_auth#58]
I've added the flutter plugin to pubspec.yaml and did a get.

The activity shows as red.  Is there something else I need to add so that I can add the CallbackActivity to the AndroidManifest?

**Comment by LinusU** [comment]
> The activity shows as red

Is this the only problem, or do you also get an error when building?

Closing since this is a bit old, but happy to reopen if you still are having problems.

Also, check out our new troubleshooting section:
https://github.com/LinusU/flutter_web_auth#troubleshooting
