### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [LinusU/flutter_web_auth#59]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:flutter_web_auth`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
The new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by phess101** [comment]
There is a pending PR for this https://github.com/LinusU/flutter_web_auth/pull/60

**Comment by chrislaurie-bs** [comment]
I support null-safety for this package. If the author is no longer interested in maintaining the package, perhaps it should be forked?

**Comment by LinusU** [comment]
Fixed in [🚢 0.3.0 / 2021-04-06](https://github.com/LinusU/flutter_web_auth/releases/tag/0.3.0)
