### ISSUE TITLE
Can't compile the library

### ISSUE THREAD

**Issue by SteamGorilla** [LinusU/flutter_web_auth#6]
Hello, i'm facing this issue when i'm trying to compile my app with your lib

![Screenshot at Sep 24 16-41-22](https://user-images.githubusercontent.com/15807770/65521983-5a49a480-deea-11e9-93e4-630b28fd6440.png)

**Comment by jingjiewei** [comment]
On flutter 1.9? Xcode 11?

**Comment by SteamGorilla** [comment]
@jingjiewei on Flutter 1.9.1+hotfix.2 and XCode 11

**Comment by jingjiewei** [comment]
@SteamGorilla I think this plugin not working properly under XCode 11. My flutter version is 1.78. And I downgrade the XCode version to XCdoe 10.2.1. And it works

**Comment by SteamGorilla** [comment]
@jingjiewei Okay, i'll give it a try

**Comment by SteamGorilla** [comment]
@jingjiewei Little update, I can't use it with XCode 10.2.1 because I'm currently developing on iOS 13

**Comment by jingjiewei** [comment]
> @jingjiewei Little update, I can't use it with XCode 10.2.1 because I'm currently developing on iOS 13

Ha, if you only have ios13 device, then you can not debug is XCode 10.2.1, but the release build still works on ios 13. I developed under ios12 and just do some verify work on ios 13

**Comment by LinusU** [comment]
@SteamGorilla would you mind testing again with the newly released version 0.1.2? I tried building with Xcode 11 & iOS 13, and it worked for me!

**Comment by SteamGorilla** [comment]
@LinusU It works like a charm on iOS now ! But I can't capture the callback on Android, even if I add the required lines in my AndroidManifest.xml

**Comment by SteamGorilla** [comment]
Hey @LinusU Do you have some updates with this issue ? I can't go production at the moment with this issue on Android :/

**Comment by jingjiewei** [comment]
> Hey @LinusU Do you have some updates with this issue ? I can't go production at the moment with this issue on Android :/

Any error message you can provide? if it's compile kotlin version issue, check this https://github.com/LinusU/flutter_web_auth/issues/9

**Comment by SteamGorilla** [comment]
Sadly no, I don't have any error messages. It just don't capture the callback and i end with an infinte loop while my android app tries to get an access token

**Comment by jingjiewei** [comment]
> Sadly no, I don't have any error messages. It just don't capture the callback and i end with an infinte loop while my android app tries to get an access token

I guess it's caused by you didn't config the callback schema correctly. Probably paste the config in manifest and your browser redirect url

**Comment by SteamGorilla** [comment]
I don't understand why because it works perfectly on iOS i'll give a look

**Comment by SteamGorilla** [comment]
![image](https://user-images.githubusercontent.com/15807770/69190696-3b017900-0b21-11ea-8f68-83cd2ed7cc24.png)
So this what I have in my Android Manifest

**Comment by jingjiewei** [comment]
> ![image](https://user-images.githubusercontent.com/15807770/69190696-3b017900-0b21-11ea-8f68-83cd2ed7cc24.png)
> So this what I have in my Android Manifest

what's the "redirect_uri" of Chrome Tab?

**Comment by SteamGorilla** [comment]
in my Chrome tab, I get exactly the redirect_url i want. But the app is  is not able to capture and parse this url on Android I guess

And this is what i have in my authenticate :
![image](https://user-images.githubusercontent.com/15807770/69191568-0e4e6100-0b23-11ea-92bd-aed9a3cc59f5.png)

**Comment by jingjiewei** [comment]
> in my Chrome tab, I get exactly the redirect_url i want. But the app is is not able to capture and parse this url on Android I guess
> 
> And this is what i have in my authenticate :
> ![image](https://user-images.githubusercontent.com/15807770/69191568-0e4e6100-0b23-11ea-92bd-aed9a3cc59f5.png)

it's caused by redirect_url not match the schema you configureded, if you don't provide detail, no one can help, callbackUrlScheme value, actual browser uri....

**Comment by SteamGorilla** [comment]
Okay

So this is what I have exact in my AndroidManifest:
![image](https://user-images.githubusercontent.com/15807770/69194093-96833500-0b28-11ea-84b2-6e811c5482f3.png)

and the value of redirectURL in callbackUrlScheme:
![image](https://user-images.githubusercontent.com/15807770/69194159-bdda0200-0b28-11ea-95f3-da0a50327ac3.png)

Do you need other details ?

**Comment by jingjiewei** [comment]
try to remove the "://" in xml and url first, if still not working

xml change to: <data android:scheme="greencom" />
redirectURL change to "greencom"
make actually chrome-tab redirect_url like: "greencom://**********"

**Comment by SteamGorilla** [comment]
I can't change the redirect url, it's actually set by the backend team :(

**Comment by SteamGorilla** [comment]
I find that my "//" are replace by %2F%2F in my Chrome tab

**Comment by lucavinci** [comment]
Does anyone have any idea what could be the issue of it only working on older Xcode versions? I am struggling on getting this plugin to work on iOS. It only works in debug mode

**Comment by SteamGorilla** [comment]
@lucavinci Did you add this in your Info.plist ? : 

`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>YOUR_REDIRECT_URI</string>
			</array>
		</dict>
	</array>`

**Comment by LinusU** [comment]
@SteamGorilla can you try to remove "://" from the Android Manifest `android:scheme` attribute?

**Comment by lucavinci** [comment]
> @lucavinci Did you add this in your Info.plist ? :
> 
> ```
> <key>CFBundleURLTypes</key>
> 	<array>
> 		<dict>
> 			<key>CFBundleURLSchemes</key>
> 			<array>
> 				<string>YOUR_REDIRECT_URI</string>
> 			</array>
> 		</dict>
> 	</array>
> ```

I did, and everything is working well when I use flutter run (debug mode), but in flutter build (release mode) I get this error:

```
    /Users/lucavinci/yusic/app/ios/Runner/GeneratedPluginRegistrant.m:10:9:
    fatal error: module 'flutter_web_auth' not found
    @import flutter_web_auth;
     ~~~~~~~^~~~~~~~~~~~~~~~
    1 error generated.
    error: the following command failed with exit code 1 but produced no further
    output
    CompileC
    /Users/lucavinci/Library/Developer/Xcode/DerivedData/Runner-gzvuspdnmzbhzxbo
    yufomcnpbdmc/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runne
    r.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
    /Users/lucavinci/yusic/app/ios/Runner/GeneratedPluginRegistrant.m normal
    arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

**Comment by SteamGorilla** [comment]
@LinusU I've removed the "://". Works like a charm !

**Comment by LinusU** [comment]
Awesome 👍
