### ISSUE TITLE
Android login will cause PlatformException(CANCELED, User canceled login)

### ISSUE THREAD

**Issue by MagicalTux** [LinusU/flutter_web_auth#62]
We're using the same scheme for various things in the app, and things used to work fine until #28 

Since we've upgraded flutter_web_auth all login attempts on android result in `PlatformException(CANCELED, User canceled login, null, null)`

After some research it seems that `_cleanUpDanglingCalls` is [called on resume](https://github.com/LinusU/flutter_web_auth/pull/28/files#diff-5c0bcfc049f3db8b5c2fbdddd6893160534df9c75da3bfde56aab3c13c5ce7bdR24) and this causes the login attempt to be cancelled prior to being able to complete.

Delaying `_cleanUpDanglingCalls` on resume could fix the issue, but I wonder if there'd be a better way to fix that.

**Comment by danielmintz** [comment]
me too
