### ISSUE TITLE
Merging of PR's

### ISSUE THREAD

**Issue by junying1** [LinusU/flutter_web_auth#63]
First of all, I want to thank @LinusU for a great plugin. It's relied on by so many people in the Flutter community. I rely on it, through oauth2_client, another great plugin by @okrad, in my commercial app.

As Flutter, Dart, iOS, and Android continue to evolve and introduce more and more changes, some breaking, I find myself really needing some of the PR's, and other functionality. In particular, issues #59 null safety support, #53 suppress warning message from iOS 13, and #37 Android CustomTab not closing are impacting user experience. So I forked the repo and merged @nonameden's #60 null safety PR, @matthewtsmith's #38 iOS 13 warning PR, and @ThexXTURBOXx's #42 closing Android CustomTab PR. I have tested on 2 projects, and so far they work well. I'm going to be releasing a commercial app built with it the next couple of weeks. The fork is git@github.com:junying1/flutter_web_auth.git. All the credit go to the PR creators, @LinusU, and other contributors. You can include it in your pubspec.yaml as:
  flutter_web_auth:
    git:
      url: git@github.com:junying1/flutter_web_auth.git

For those using @okrad's oauth2_client, I created a fork git@github.com:junying1/oauth2_client.git, branch alt_flutter_web_auth. It depends on the flutter_web_auth fork above. It also has a small non-functional (refactoring) PR @okrad is reviewing, and hopefully merge in the near future. You can include it in your pubspec.yaml as:
  oauth2_client:
    git:
      url: git@github.com:junying1/oauth2_client.git
      ref: alt_flutter_web_auth

I'll probably start on web app support to work with Flutter 2, sooner rather than later.

I created these 2 forks for my own use. If anyone is interested in using, I'm happy to provide whatever support I can. Always appreciate other eyes to test and contribute.

Thanks again to @LinusU and everyone else.

**Comment by LinusU** [comment]
Sorry for the delay here, I think all the mentioned PRs are merged and released with [🚢 0.3.1 / 2021-09-07](https://github.com/LinusU/flutter_web_auth/releases/tag/0.3.1)

**Comment by junying1** [comment]
Thanks LinusU. Can you please take a look and merge #68 as well? Also, how about adding maintainers?
