### ISSUE TITLE
[IOS] How to change title popup start

### ISSUE THREAD

**Issue by beheobong** [LinusU/flutter_web_auth#71]
<img width="398" alt="Screen Shot 2021-05-01 at 09 18 12" src="https://user-images.githubusercontent.com/53457593/116768105-72868b80-aa5e-11eb-9949-2d549f9f3695.png">
I want change name "flutter_web_auth_example" in ios. How i do that? thanks

**Comment by LinusU** [comment]
iOS will use the name of your app there, so when you use this in your actual app instead of in the example it will use the name of your app.

This is not controllable from our perspective, so the only way to change it is to change the name of your entire app...
