### ISSUE TITLE
The new intent don't close after redirecting back to the main app

### ISSUE THREAD

**Issue by pinguluk** [LinusU/flutter_web_auth#88]
So, when you do the **FlutterWebAuth.authenticate** and the user is redirected back to the main app, the activity with the browser is still open and you need to close it manually on the phone.

How to fix this?

**Comment by ThexXTURBOXx** [comment]
In the new release 0.3.1, there is a flag `preferEphemeral` for the `authenticate` method. If you set it to `true`, it will handle this properly.
