### ISSUE TITLE
 PlatformException(CANCELED, User canceled login, null, null)

### ISSUE THREAD

**Issue by shahid898** [LinusU/flutter_web_auth#92]
flutter_web_auth all login attempts on android result in PlatformException(CANCELED, User canceled login, null, null)

After some research it seems that _cleanUpDanglingCalls is called on resume and this causes the login attempt to be cancelled prior to being able to complete.

Delaying _cleanUpDanglingCalls on resume could fix the issue, but I wonder if there'd be a better way to fix that.

**Comment by supratikkoley** [comment]
How did you solve this issue? @shahid898

**Comment by lovecraftHP** [comment]
@shahid898 yo, Can you explain how did you solve this? I got the same problem with the second version of this package (**_Flutter_web_auth_2_**)
