### ISSUE TITLE
How to remove persistent cookies?

### ISSUE THREAD

**Issue by pinguluk** [LinusU/flutter_web_auth#94]
Basically I added authentication with Spotify and when someone logs in to retrieve the access token, the cookies are stored in the browser and you can't log out / change the account.

Some solutions I've found:

1. Open a new ```FlutterWebAuth.authenticate``` to ```https://spotify.com/logout```, so the cookies will be cleared out (but you have to close it manually afterwards)
2. Set ```show_dialog: true``` in the authorization request for Spotify, which will display a confirmation each time the user logs in with the possibility to click on ```Not you?``` to change the account, which is kinda annoying

Isn't there any option to open a FlutterWebAuth that doesn't store the cookies in the browser and just retrieves the access token?

**Comment by LinusU** [comment]
Unfortunately I don't know of any APIs exposed to do this with, so I don't think that there is any way for us to support this.

Happy to reopen this if there is any way to do this with native code!

**Comment by vasile-baluta** [comment]
I just needed a solution to this problem my self and Open a new FlutterWebAuth.authenticate to logout url of you service works very well. If you use the same redirect url you used when you logged in, then FlutterWebAuth will use the auth.html to redirect to the app so no need to close it manually. In my case I am using Azure ADB2C.
